<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8"/>
  <link href="https://www.aht.li/3935826/xenippa1.ttf" rel="stylesheet" />
  </head>

<style>
  @font-face {
  font-family: 'Xenippa';
  src: url('https://dafontsfree.net//wp-content/fonts/gothic/medieval/FontsFree-Net-xenippa1.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
  
  .fiche-rpg {
    max-width: 550px;
    margin: 30px auto;
    background: #333333;
    color: #e6e6e6;
    font-family: 'Georgia', serif;
    border: 2px solid #444;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 0 15px rgba(0,0,0,0.6);
  }

  .fiche-banner {
    width: 100%;
    height: 250px;
background: linear-gradient(to bottom, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0) 100%), url(https://univers.yuimen.net/styles/Hexagon/theme/images/banner-4.png) center / cover no-repeat;
  mask-image: linear-gradient(to bottom, black 75%, transparent 100%);
  -webkit-mask-image: linear-gradient(to bottom, black 75%, transparent 100%);
  }

  .fiche-section {
    padding: 20px;
    margin-top: -100px;
      position: relative;
  }

  .fiche-section h2 {
    font-size: 55px;
    color: #8080BF;
    text-align: center;
    margin-bottom: 15px;
    letter-spacing: 2px;
      font-family: 'Xenippa', serif;
  text-shadow: 2px 2px 6px rgba(0, 0, 0, 0.9);
  }

  .fiche-section p {
    line-height: 1.7;
    font-size: 15px;
    text-align: justify;
  }

  .fiche-buttons {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 10px;
    padding: 15px;
    background: #111;
  }

  .fiche-buttons a {
    flex: 1;
    min-width: 120px;
    text-align: center;
    text-decoration: none;
    background: #2e2e2e;
    padding: 10px 15px;
    color: #e6e6e6;
    border-radius: 8px;
    transition: 0.3s;
  }

  .fiche-buttons a:hover {
    background: #8080bf;
    color: #1a1a1a;
  }
  
.fiche-infos {
    padding: 0px 20px 20px 20px;
  }

  .fiche-infos h3 {
    font-size: 20px;
    color: #8080BF;
    margin-bottom: 10px;
    border-bottom: 1px solid #444;
    padding-bottom: 5px;
  }

  .fiche-infos ul {
    list-style: none;
    padding-left: 0;
    line-height: 1.6;
  }

  .fiche-footer {
    text-align: center;
    padding: 12px;
    background: #111;
    font-size: 13px;
    color: #aaa;
  }
</style>
<body>
<div class="fiche-rpg">

  <!-- Bannière -->
  <div class="fiche-banner"></div>

  <!-- Contexte -->
  <div class="fiche-section">
    <h2>Yuimen</h2>
        <h3>Contexte</h3>
    <p>
Yuimen est un univers médiéval-fantastique avec un background enrichi par des années de fendage de poire et des systèmes de jeu flexibles pour faciliter ledit fendage de poire. Bien que nous n'imposons pas d'exigences quant à la qualité d'écriture, nous encourageons la créativité avec un système de progression via commentaires (un maître de jeu lit et commente un RP en donnant son avis de lecteur en plus de récompenser les actions effectuées).
      <br/>
      Nous accompagnons aussi les joueurs dans la création de leurs propres classes à partir de certains paliers, une tradition qui récompense les joueurs assidus avec des possibilités qui leurs sont propres.
      <br/>
      En sus, nous impliquons régulièrement les joueurs dans des événements et quêtes à échelle variable, permettant un hybride entre écriture participative et longues sessions de JdR sur table. Ces événements ont souvent des ramifications particulières susceptibles d'influencer le background et placent les joueurs en première ligne de l'histoire du monde.
    </p>
  </div>

  <!-- Boutons infos -->
  <div class="fiche-buttons">
    <a href="#">Forum</a>
    <a href="#">Règlement</a>
    <a href="#">Personnages</a>
    <a href="#">Histoire</a>
  </div>

  <!-- Section infos -->
  <div class="fiche-infos">
    <h3>Informations</h3>
    <ul>
      <li><b>Type :</b> Forum RPG Médiéval-Fantastique</li>
      <li><b>Ouverture :</b> 2001</li>
      <li><b>Âge conseillé :</b> 16+ (???)</li>
      <li><b>Avatars :</b> Illustrés</li>
      <li><b>Nombre de lignes :</b> (???)</li>
    </ul>
  </div>

  <!-- Footer -->
  <div class="fiche-footer">
    &copy; 2001-2025 - <i>Yuimen</i>
  </div>
</div>

</body>
</html>
